### ISSUE TITLE
weapon_ut2004_sniper

### ISSUE THREAD

**Issue by henkeswe** [LambdaHidden/UT2004SWEPs#6]
Player [4][Henke] ERR: [Unreal Tournament 2004 SWEPs]   lua/weapons/weapon_ut2004_sniper/shared.lua:77: attempt to call method 'WeaponSoundSound' (a nil value)
  1. unknown -   lua/weapons/weapon_ut2004_sniper/shared.lua:77

**Comment by LambdaHidden** [comment]
Already aware, thought it only happened to the lightning gun, thanks.
